# Generated by Django 3.0.1 on 2019-12-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=30)),
                ('rarity', models.CharField(max_length=30)),
                ('card_class', models.CharField(max_length=30)),
                ('card_type', models.CharField(max_length=30)),
                ('api_id', models.CharField(max_length=10)),
            ],
        ),
    ]
