# Generated by Django 3.0.1 on 2019-12-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradecenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
    ]
