# Generated by Django 3.0.1 on 2019-12-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradecenter', '0002_remove_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='api_id',
            field=models.CharField(max_length=30),
        ),
    ]
