# Generated by Django 3.0.1 on 2019-12-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradecenter', '0003_auto_20191230_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='insert image here', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
