# Generated by Django 3.0.1 on 2020-01-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradecenter', '0004_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(max_length=500, upload_to='gallery/'),
        ),
    ]
