# Generated by Django 3.0.1 on 2020-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradecenter', '0006_deck_transaction_usercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
